config/routes.rb
Rails.application.routes.draw do


  root to: "vehicles#index"
  get "/show" => "vehicles#index", :as => :index

  namespace :api do
    namespace :v1 do
      post "/gps" => "waypoint#create", :as => :create
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord

  has_many :waypoints

  validates_uniqueness_of :vehicle_identifier


  def self.current_waypoint vehicle
    return Waypoint.where(vehicle_identifier: vehicle.vehicle_identifier).order('sent_at DESC').first
  end

  def get_vehicles_waypoints
    vehicles = Vehicle.all
    waypoints = []

    vehicles.each do |vehicle|
      waypoints << Vehicle.current_waypoint(vehicle)
    end

    return waypoints
  end


end

app/models/waypoint.rb
    class Waypoint < ApplicationRecord

      belongs_to :vehicle


      def create_waypoint waypoint


        if vehicle = Vehicle.find_by_vehicle_identifier(waypoint[:vehicle_identifier])
          newVehicle = vehicle
        else
          newVehicle = Vehicle.new
          newVehicle.vehicle_identifier = waypoint[:vehicle_identifier]
          newVehicle.save
        end


        newWaypoint = Waypoint.new
        newWaypoint.longitude = waypoint[:longitude]
        newWaypoint.latitude = waypoint[:latitude]
        newWaypoint.sent_at = waypoint[:sent_at].to_datetime
        newWaypoint.vehicle_identifier = waypoint[:vehicle_identifier]
        newWaypoint.vehicle = newVehicle

        puts newWaypoint.valid?
        puts newWaypoint.errors.messages

        newWaypoint.save
      end

    end

app/controllers/api/v1/waypoint_controller.rb
class Api::V1::WaypointController < ApplicationController

  skip_before_action :verify_authenticity_token



  def create
    @waypoint = Waypoint.new

    @waypoint.create_waypoint(params)

    render plain: :nothing, status: :ok

  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
  skip_before_action :verify_authenticity_token

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicle = Vehicle.new
    @vehicles = @vehicle.get_vehicles_waypoints

    @hash = Gmaps4rails.build_markers(@vehicles) do |vehicle, marker|
      marker.lat vehicle.latitude
      marker.lng vehicle.longitude
      marker.infowindow vehicle.vehicle_identifier
    end
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:vehicle_identifier)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vehicle Tracking</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="//maps.google.com/maps/api/js?key=AIzaSyDBfhpUVWZwt1OkeAQtIZDUWdAzC5IxBn8"></script>
    <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
    <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :vehicle_identifier %>
    <%= form.text_field :vehicle_identifier, id: :vehicle_vehicle_identifier %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vehicles</h1>

<table>
  <thead>
  <tr>
    <th>Vehicle ID</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th>Position Date</th>
  </tr>
  </thead>

  <tbody>
  <% @vehicles.each do |vehicle| %>
      <tr>
        <td><%= vehicle.vehicle_identifier %></td>
        <td><%= vehicle.latitude %></td>
        <td><%= vehicle.longitude %></td>
        <td><%= vehicle.sent_at %></td>

      </tr>
  <% end %>
  </tbody>
</table>

<div style='width: 800px;'>
  <div id="map" style='width: 800px; height: 400px;'></div>
</div>


<br>


<script>
    handler = Gmaps.build('Google');
    handler.buildMap({provider: {}, internal: {id: 'map'}}, function () {
        markers = handler.addMarkers(<%=raw @hash.to_json %>);
        handler.bounds.extendWith(markers);
        handler.fitMapToBounds();
    });
</script>

app/views/vehicles/new.html.erb
<h1>New Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vehicle identifier:</strong>
  <%= @vehicle.vehicle_identifier %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>